### ISSUE TITLE
Nodes data frame columns

### ISSUE THREAD

**Issue by atredennick** [andreashandel/flowdiagramr#14]
From @andreashandel:
_why do nodes in input_structure object not have xstart/xend, ystart/yend to determine size of box, and only have x and y?_

**Comment by atredennick** [comment]
The nodes are drawn using `geom_tile()`, which takes the center position (`x` and `y`) and then a `width` and `height` argument. I am currently setting `height = 1` and `width = 1` to get perfect squares:

```
 geom_tile(data = nodes,
              aes(x = x, y = y),
              color = node_outline_color,
              fill = node_fill_color,
              width = 1,
              height = 1)
```

**Comment by andreashandel** [comment]
We should allow users to specify box size. And for manual adjustment of boxes and arrows through editing the input data frames, it's probably better if that data frame contains xmin/xmax, etc. instead of center and width of boxes. This makes it easier to align arrows with boxes. So my suggestion is that prepare_diagram returns xmin/xmax for boxes the same format as for arrows, and inside make_diagram we can convert to the way geom_tile needs it.

**Comment by atredennick** [comment]
This is implemented with `geom_rect`.
