### ISSUE TITLE
Argument for node placement on grid

### ISSUE THREAD

**Issue by atredennick** [andreashandel/flowdiagramr#7]
Add a new argument that allows the user to specify a grid and where each state variable (node) should be placed. This will be a matrix.

**Comment by andreashandel** [comment]
Maybe consider data frame instead/in addition to matrix, since these days more users seem to be using dataframes?
Need to ensure that the data frame contains all variables, and nothing else. So some error checking needed in case user supplies a DF that has variable names that are not in the mbmodel (or equivalent) structure or leaves out variable names.

**Comment by andreashandel** [comment]
suggestion/idea. When user creates their model, they can 

EITHER supply the varlabels either as a vector, e.g. varlabels = c("S","I","R") 

OR they can supply it as a matrix, that defines a grid structure. E.g. this would define a 2x3 matrix with S and R in column 1 and 3 in the first row and I in column 2 in the 2nd row:

data = c("S","","R",
               "","I","")
varlabels = matrix(data,nrow = 2, byrow = TRUE)

The numbers of rows and columns in the matrix defines the grid/layout for the plot. The labels are placed where they want it, all other slots empty.
Is just an idea, if you think of another/better way to do it, also ok.

**Comment by atredennick** [comment]
This has been implemented.
